version: '2.0'

services:

    influxdb:
        image: influxdb
        container_name: influxdb
        ports:
          - 4286:8086
        volumes:
          - D:\Users\TOS\docker\volumes\influxdb:/var/lib/influxdb
#          - /volume1/docker/influxdb:/var/lib/influxdb
        networks:
          - net
#        deploy:
#          placement:
#            constraints:
#              - node.role == manager
    mysql:

        image: mysql:5.7.22
        restart: on-failure
        container_name: mysql
        ports:
          - 3306:3306
        volumes:
          - D:\Users\TOS\docker\volumes\mysql:/var/lib/mysql
#          -  /volume1/docker/mysql:/var/lib/mysql
        environment:
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

    ui:
        image: chronograf:alpine
        container_name: chronograf
        ports:
          - 4288:8888
        depends_on:
          - influxdb
        links:
          - influxdb
        networks:
          - net
        command: chronograf --influxdb-url=http://influxdb:8086

    telegraf:
        build: telegraf/.
        image: shocki/telegraf
        container_name: telegraf
        environment:
          - DOCKER_API_VERSION=1.35
#        volumes:
#          - /var/run/docker.sock:/var/run/docker.sock:ro
        networks:
          - net

    mosquitto:
        build: mosquitto/.
        container_name: mosquitto
        image: shocki/mosquitto
        ports:
            - 1883:1883
        networks:
          - net

    facerec:
        container_name: facerec
        image: shocki/facerec:v0.1.1
        ports:
            - 8081:80
        volumes:
          - D:\Users\TOS\docker\volumes\facerec:/data

networks:
  net:
    driver: bridge #overlay

  rsync:
    driver: bridge #overlay