version: '3.4'

services:

    influxdb:
        image: influxdb
        container_name: influxdb
        ports:
          - 4286:8086
#        volumes:
#          - D:\Users\TOS\docker\volumes\influxdb:/var/lib/influxdb
#          - /volume1/docker/influxdb:/var/lib/influxdb
        networks:
          - net
#        deploy:
#          placement:
#            constraints:
#              - node.role == manager

    ui:
        image: chronograf:alpine
        container_name: chronograf
        ports:
          - 4288:8888
        networks:
          - net
        command: chronograf --influxdb-url=http://influxdb:8086

    telegraf:
        build: telegraf/.
        image: shocki/telegraf
        container_name: telegraf
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
        secrets:
          - telegraf_mqtt_pw
        networks:
          - net

    mosquitto:
        build: mosquitto/.
        image: shocki/mosquitto
        container_name: mqtt
#        volumes:
#          - /volume1/docker/mosquitto:/credentials
        ports:
            - 1883:1883
        secrets:
          - source: mqtt_passwd
            target: passwd

        networks:
          - net
#
networks:
  net:
    driver:
      overlay

secrets:
  mqtt_passwd:
    external: true
  telegraf_mqtt_pw:
    external: true