version: '2.0'

services:

    influxdb:
        image: influxdb:1.8.4-alpine
        container_name: influxdb
        ports:
          - 4286:8086
        volumes:
#          - D:\Users\TOS\docker\volumes\influxdb:/var/lib/influxdb
          - /volume1/docker/influxdb:/var/lib/influxdb
        networks:
          - net

    ui:
        image: chronograf:1.8.8-alpine
        container_name: chronograf
        ports:
          - 4288:8888
        networks:
          - net
        volumes:
          - /volume1/docker/chronograf:/var/lib/chronograf
        command: chronograf --influxdb-url=http://influxdb:8086

    telegraf:
        image: telegraf:1.17.3-alpine
        container_name: telegraf
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
          - ./telegraf/telegraf.conf:/telegraf.conf
        command: telegraf --config ./telegraf.conf
        networks:
          - net

    mosquitto:
        image: eclipse-mosquitto:2.0.8
        container_name: mqtt
        volumes:
          - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
          - ~/docker/secrets/mqtt:/run/secrets:ro
        ports:
            - 1883:1883
        networks:
          - net

networks:
  net:
    driver:
      bridge
