version: "3.0"
services:

    influxdb:
        image: influxdb
#        name: influx-db
        ports:
          - 4286:8086
#        volumes:
#          - ./data:/var/lib/influxdb

    chronograf:
        image: chronograf:alpine
#        name: influx-chrono
        ports:
          - 4288:8888
        depends_on:
          - influxdb
        links:
          - influxdb
        command: chronograf --influxdb-url=http://influxdb:8086

    telegraf:
        build: telegraf/.
#        name: influx-telegraf
        depends_on:
          - influxdb
          - mosquitto
        links:
          - influxdb
          - mosquitto

    mosquitto:
        build: mosquitto/.
        image: shocki/mosquitto
#        name: mqtt-broker
        ports:
            - 1883:1883

        depends_on:
            - influxdb

        links:
            - influxdb
