version: '2.0'

services:

    influxdb:
        image: influxdb
        container_name: influxdb
        ports:
          - 4286:8086
        volumes:
          - D:\Users\TOS\docker\volumes\influxdb:/var/lib/influxdb
#          - /volume1/docker/influxdb:/var/lib/influxdb
        networks:
          - net
#        deploy:
#          placement:
#            constraints:
#              - node.role == manager
    mysql:

        image: mysql:5.7.22
        restart: on-failure
        container_name: mysql
        ports:
          - 3306:3306
        volumes:
          - D:\Users\TOS\docker\volumes\mysql:/var/lib/mysql
#          -  /volume1/docker/mysql:/var/lib/mysql
        environment:
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

    rsync.to:
        image: shocki/rsync-to
        container_name: rsync.to
        networks:
          - rsync
        volumes:
          - D:\Users\TOS\docker\volumes\data:/data

    solr:
        image: shocki/solr
        container_name: solr
        ports:
          - 8983:8983
        volumes:
           - D:\Users\TOS\docker\volumes\data:/data
           - D:\Users\TOS\docker\volumes\solr:/opt/solr/server/solr/mycores

    ui:
        image: chronograf:alpine
        ports:
          - 4288:8888
        depends_on:
          - influxdb
        links:
          - influxdb
        networks:
          - net
        command: chronograf --influxdb-url=http://influxdb:8086

#    telegraf:
#        build: telegraf/.
#        image: shocki/telegraf
#        environment:
#          - DOCKER_API_VERSION=1.35
#        volumes:
#          - /var/run/docker.sock:/var/run/docker.sock:ro
#        networks:
#          - net

    mosquitto:
        build: mosquitto/.
        image: shocki/mosquitto
        ports:
            - 1883:1883
        networks:
          - net

networks:
  net:
    driver: bridge #overlay

  rsync:
    driver: bridge #overlay

#volumes:
#  data:
#    driver: local